/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymanagementsystemclient.GUIs;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ahmedwaleed
 */
public class DoctorSalary extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudents
     */
    public DoctorSalary() {
        initComponents();
    }

    public JLabel getTestlbl() {
        return testlbl;
    }

    public JTextField getIdtxt() {
        return idtxt;
    }

    public JTextField getSalarytxt() {
        return salarytxt;
    }

    public JButton getUpdatesalarybtn() {
        return updatesalarybtn;
    }

  

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTable getStudentstbl() {
        return doctors;
    }

    public JButton getBackbtn() {
        return backbtn;
    }

    public JTable getDoctors() {
        return doctors;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

  

  

    

    public JTextField getIdtb() {
        return idtxt;
    }

    public JTextField getLnametb() {
        return salarytxt;
    }


    public JButton getUpdatestudentbtn() {
        return updatesalarybtn;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        doctors = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        salarytxt = new javax.swing.JTextField();
        updatesalarybtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        testlbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(doctors);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 88, 876, 155));

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Doctor Salary");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 9, 521, 61));

        idtxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 130, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Salary");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 100, 30));

        salarytxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(salarytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 130, 30));

        updatesalarybtn.setBackground(new java.awt.Color(0, 0, 0));
        updatesalarybtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        updatesalarybtn.setForeground(new java.awt.Color(255, 255, 255));
        updatesalarybtn.setText("Update Salary");
        getContentPane().add(updatesalarybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        backbtn.setBackground(new java.awt.Color(0, 0, 0));
        backbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back to menu");
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 160, 30));

        testlbl.setForeground(new java.awt.Color(255, 255, 255));
        testlbl.setText("jLabel3");
        getContentPane().add(testlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Grad2.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JTable doctors;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField salarytxt;
    private javax.swing.JLabel testlbl;
    private javax.swing.JButton updatesalarybtn;
    // End of variables declaration//GEN-END:variables
}
