/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymanagementsystemclient.GUIs;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ahmedwaleed
 */
public class DoctorMaterials extends javax.swing.JFrame {

    /**
     * Creates new form DoctorMaterials
     */
    public DoctorMaterials() {
        initComponents();
    }

    public JTable getDocstable() {
        return docstable;
    }

    public JLabel getIdlbl() {
        return idlbl;
    }

    public JTextField getCourseidtb() {
        return courseidtb;
    }

    public JTextField getIdtb() {
        return idtb;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JTextField getTitletb() {
        return titletb;
    }

    public JTextField getViisibilitytb() {
        return viisibilitytb;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JButton getShowbtn() {
        return showbtn;
    }

    public JButton getAddbtn() {
        return addbtn;
    }

    public JButton getDeletebtn() {
        return deletebtn;
    }

    public JButton getBackbtn() {
        return backbtn;
    }

    public JButton getUpdatebtn() {
        return updatebtn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        docstable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        showbtn = new javax.swing.JButton();
        idlbl = new javax.swing.JLabel();
        deletebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        courseidtb = new javax.swing.JTextField();
        viisibilitytb = new javax.swing.JTextField();
        titletb = new javax.swing.JTextField();
        idtb = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(docstable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 123, 798, 132));

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Doctor Materials");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 42, -1, 63));

        showbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        showbtn.setForeground(new java.awt.Color(0, 0, 0));
        showbtn.setText("Show");
        jPanel1.add(showbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 350, 136, -1));

        idlbl.setText("jLabel2");
        jPanel1.add(idlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 21, 44, 51));

        deletebtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(0, 0, 0));
        deletebtn.setText("Delete");
        jPanel1.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 439, 136, -1));

        updatebtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(0, 0, 0));
        updatebtn.setText("Update");
        jPanel1.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 439, 136, -1));

        addbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addbtn.setForeground(new java.awt.Color(0, 0, 0));
        addbtn.setText("Add");
        jPanel1.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 439, 136, -1));

        backbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        backbtn.setText("Back");
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 455, 133, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Visibility");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 90, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CourseID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Title");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 90, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 30));

        courseidtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(courseidtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 110, 30));

        viisibilitytb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(viisibilitytb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 110, 30));

        titletb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(titletb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 110, 30));

        idtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(idtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 269, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorMaterials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorMaterials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorMaterials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorMaterials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorMaterials().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField courseidtb;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTable docstable;
    private javax.swing.JLabel idlbl;
    private javax.swing.JTextField idtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton showbtn;
    private javax.swing.JTextField titletb;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField viisibilitytb;
    // End of variables declaration//GEN-END:variables
}
