/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymanagementsystemclient.GUIs;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ahmedwaleed
 */
public class ManageDoctors extends javax.swing.JFrame {

    /**
     * Creates new form ManageDoctors
     */
    public ManageDoctors() {
        initComponents();
    }



    public JButton getBackbtn() {
        return backbtn;
    }

    public JTextField getBanktb() {
        return banktb;
    }

    public JButton getAdddoctorbtn() {
        return adddoctorbtn;
    }

    public JButton getDeletedoctorbtn() {
        return deletedoctorbtn;
    }

    public JButton getUpdatedoctorbtn() {
        return updatedoctorbtn;
    }


    public JTable getDoctorstbl() {
        return doctorstbl;
    }

    public JTextField getEmailtb() {
        return emailtb;
    }

    public JTextField getFnametb() {
        return fnametb;
    }

    public JTextField getIdtb() {
        return idtb;
    }

    public JTextField getLnametb() {
        return lnametb;
    }

    public JTextField getPasswordtb() {
        return passwordtb;
    }

    public JTextField getSalarytb() {
        return salarytb;
    }

    public JLabel getTestlbl() {
        return testlbl;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        testlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorstbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailtb = new javax.swing.JTextField();
        idtb = new javax.swing.JTextField();
        fnametb = new javax.swing.JTextField();
        passwordtb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        banktb = new javax.swing.JTextField();
        lnametb = new javax.swing.JTextField();
        salarytb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        adddoctorbtn = new javax.swing.JButton();
        updatedoctorbtn = new javax.swing.JButton();
        deletedoctorbtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        testlbl.setForeground(new java.awt.Color(255, 255, 255));
        testlbl.setText("jLabel13");
        jPanel1.add(testlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 40));

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Doctors");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 9, 480, 61));

        doctorstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(doctorstbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 88, 876, 155));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-mail");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 30));

        emailtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(emailtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 130, 30));

        idtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(idtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 130, 30));

        fnametb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(fnametb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 130, 30));

        passwordtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(passwordtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 130, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 90, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 90, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bank");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 90, 30));

        banktb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(banktb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 130, 30));

        lnametb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(lnametb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 130, 30));

        salarytb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(salarytb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 130, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Salary");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 100, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Last Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 100, 30));

        backbtn.setBackground(new java.awt.Color(0, 0, 0));
        backbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back to menu");
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 160, 30));

        adddoctorbtn.setBackground(new java.awt.Color(0, 0, 0));
        adddoctorbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        adddoctorbtn.setForeground(new java.awt.Color(255, 255, 255));
        adddoctorbtn.setText("Add Doctor");
        adddoctorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddoctorbtnActionPerformed(evt);
            }
        });
        jPanel1.add(adddoctorbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, -1));

        updatedoctorbtn.setBackground(new java.awt.Color(0, 0, 0));
        updatedoctorbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        updatedoctorbtn.setForeground(new java.awt.Color(255, 255, 255));
        updatedoctorbtn.setText("Update Doctor");
        jPanel1.add(updatedoctorbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        deletedoctorbtn.setBackground(new java.awt.Color(0, 0, 0));
        deletedoctorbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deletedoctorbtn.setForeground(new java.awt.Color(255, 255, 255));
        deletedoctorbtn.setText("Delete Doctor");
        jPanel1.add(deletedoctorbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitymanagementsystemclient/GUIs/abstract-1780378_960_720.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adddoctorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddoctorbtnActionPerformed

    }//GEN-LAST:event_adddoctorbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adddoctorbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField banktb;
    private javax.swing.JButton deletedoctorbtn;
    private javax.swing.JTable doctorstbl;
    private javax.swing.JTextField emailtb;
    private javax.swing.JTextField fnametb;
    private javax.swing.JTextField idtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lnametb;
    private javax.swing.JTextField passwordtb;
    private javax.swing.JTextField salarytb;
    private javax.swing.JLabel testlbl;
    private javax.swing.JButton updatedoctorbtn;
    // End of variables declaration//GEN-END:variables
}
