/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymanagementsystemclient.GUIs;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ahmedwaleed
 */
public class ManageCourses extends javax.swing.JFrame {

    /**
     * Creates new form ManageCourses
     */
    public ManageCourses() {
        initComponents();
    }

    public JButton getAddcoursebtn() {
        return addcoursebtn;
    }

    public JButton getBackbtn() {
        return backbtn;
    }

    public JTable getCoursestbl() {
        return coursestbl;
    }

    public JButton getDeletecoursebtn() {
        return deletecoursebtn;
    }

    public JTextField getDocidtb() {
        return docidtb;
    }

    public JTextField getEmailtb() {
        return emailtb;
    }

    public JTextField getFacultytb() {
        return facultytb;
    }

    public JTextField getIdtb() {
        return idtb;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getTestlbl() {
        return testlbl;
    }

    public JTextField getTitletb() {
        return titletb;
    }

    public JButton getUpdatecoursebtn() {
        return updatecoursebtn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursestbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idtb = new javax.swing.JTextField();
        emailtb = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        titletb = new javax.swing.JTextField();
        facultytb = new javax.swing.JTextField();
        docidtb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        testlbl = new javax.swing.JLabel();
        deletecoursebtn = new javax.swing.JButton();
        updatecoursebtn = new javax.swing.JButton();
        addcoursebtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Courses");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 480, 61));

        coursestbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(coursestbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 88, 876, 155));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 70, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("E-mail");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 70, 30));

        idtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(idtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 130, 30));

        emailtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(emailtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 130, 30));

        backbtn.setBackground(new java.awt.Color(0, 0, 0));
        backbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back to menu");
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 160, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Faculty");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 90, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Title");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 90, 30));

        titletb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(titletb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 130, 30));

        facultytb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(facultytb, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 130, 30));

        docidtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(docidtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 130, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Doctor ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 100, 30));

        testlbl.setForeground(new java.awt.Color(255, 255, 255));
        testlbl.setText("jLabel13");
        jPanel1.add(testlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 90, 30));

        deletecoursebtn.setBackground(new java.awt.Color(0, 0, 0));
        deletecoursebtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deletecoursebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletecoursebtn.setText("Delete Course");
        jPanel1.add(deletecoursebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));

        updatecoursebtn.setBackground(new java.awt.Color(0, 0, 0));
        updatecoursebtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        updatecoursebtn.setForeground(new java.awt.Color(255, 255, 255));
        updatecoursebtn.setText("Update Course");
        jPanel1.add(updatecoursebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, -1));

        addcoursebtn.setBackground(new java.awt.Color(0, 0, 0));
        addcoursebtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addcoursebtn.setForeground(new java.awt.Color(255, 255, 255));
        addcoursebtn.setText("Add Course");
        addcoursebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcoursebtnActionPerformed(evt);
            }
        });
        jPanel1.add(addcoursebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitymanagementsystemclient/GUIs/abstract-1780378_960_720.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addcoursebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcoursebtnActionPerformed

    }//GEN-LAST:event_addcoursebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcoursebtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JTable coursestbl;
    private javax.swing.JButton deletecoursebtn;
    private javax.swing.JTextField docidtb;
    private javax.swing.JTextField emailtb;
    private javax.swing.JTextField facultytb;
    private javax.swing.JTextField idtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel testlbl;
    private javax.swing.JTextField titletb;
    private javax.swing.JButton updatecoursebtn;
    // End of variables declaration//GEN-END:variables
}
