/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymanagementsystemclient.GUIs;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ahmedwaleed
 */
public class ManageFaculties extends javax.swing.JFrame {

    /**
     * Creates new form ManageFaculties
     */
    public ManageFaculties() {
        initComponents();
    }



    public JButton getBackbtn() {
        return backbtn;
    }

    public JTextField getDeantb() {
        return deantb;
    }



    public JButton getAddfacbtn() {
        return addfacbtn;
    }

    public JButton getDeletefacbtn() {
        return deletefacbtn;
    }

    public JButton getUpdatefacbtn() {
        return updatefacbtn;
    }

    public JTextField getEmailtb() {
        return emailtb;
    }

    public JTable getFactbl() {
        return factbl;
    }

    public JTextField getFeestb() {
        return feestb;
    }

    public JTextField getIdtb() {
        return idtb;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTextField getNametb() {
        return nametb;
    }

    public JLabel getTestlbl() {
        return testlbl;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        factbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idtb = new javax.swing.JTextField();
        emailtb = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nametb = new javax.swing.JTextField();
        feestb = new javax.swing.JTextField();
        deantb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        testlbl = new javax.swing.JLabel();
        deletefacbtn = new javax.swing.JButton();
        updatefacbtn = new javax.swing.JButton();
        addfacbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Faculties");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 530, 61));

        factbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(factbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 88, 876, 155));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-mail");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 70, 30));

        idtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(idtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 130, 30));

        emailtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(emailtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 130, 30));

        backbtn.setBackground(new java.awt.Color(0, 0, 0));
        backbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back to menu");
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 160, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fees");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 90, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 90, 30));

        nametb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(nametb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 130, 30));

        feestb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(feestb, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 130, 30));

        deantb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(deantb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 130, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dean");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 100, 30));

        testlbl.setForeground(new java.awt.Color(255, 255, 255));
        testlbl.setText("jLabel13");
        jPanel1.add(testlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 90, 30));

        deletefacbtn.setBackground(new java.awt.Color(0, 0, 0));
        deletefacbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deletefacbtn.setForeground(new java.awt.Color(255, 255, 255));
        deletefacbtn.setText("Delete Faculty");
        jPanel1.add(deletefacbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, -1, -1));

        updatefacbtn.setBackground(new java.awt.Color(0, 0, 0));
        updatefacbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        updatefacbtn.setForeground(new java.awt.Color(255, 255, 255));
        updatefacbtn.setText("Update Faculty");
        jPanel1.add(updatefacbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        addfacbtn.setBackground(new java.awt.Color(0, 0, 0));
        addfacbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addfacbtn.setForeground(new java.awt.Color(255, 255, 255));
        addfacbtn.setText("Add Faculty");
        addfacbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfacbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addfacbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitymanagementsystemclient/GUIs/Grad2.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addfacbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfacbtnActionPerformed

    }//GEN-LAST:event_addfacbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageFaculties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageFaculties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageFaculties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageFaculties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageFaculties().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addfacbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField deantb;
    private javax.swing.JButton deletefacbtn;
    private javax.swing.JTextField emailtb;
    private javax.swing.JTable factbl;
    private javax.swing.JTextField feestb;
    private javax.swing.JTextField idtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nametb;
    private javax.swing.JLabel testlbl;
    private javax.swing.JButton updatefacbtn;
    // End of variables declaration//GEN-END:variables
}
