/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymanagementsystemclient.GUIs;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ahmedwaleed
 */
public class ManageTAs extends javax.swing.JFrame {

    /**
     * Creates new form ManageTAs
     */
    public ManageTAs() {
        initComponents();
    }

    public JButton getAddtabtn() {
        return addtabtn;
    }

    public JButton getBackbtn() {
        return backbtn;
    }

    public JTable getTAsTable() {
        return TAsTable;
    }

    public JTextField getBanktb() {
        return banktb;
    }

    public JButton getDeletetabtn() {
        return deletetabtn;
    }


    public JTextField getEmailtb() {
        return emailtb;
    }

    public JTextField getFnametb() {
        return fnametb;
    }

    public JTextField getIdtb() {
        return idtb;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTextField getLnametb() {
        return lnametb;
    }

    public JTextField getPasswordtb() {
        return passwordtb;
    }

    public JTextField getSalarytb() {
        return salarytb;
    }

    public JLabel getTestlbl() {
        return testlbl;
    }

    public JButton getUpdatetabtn() {
        return updatetabtn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        testlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        idtb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailtb = new javax.swing.JTextField();
        fnametb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        banktb = new javax.swing.JTextField();
        passwordtb = new javax.swing.JTextField();
        lnametb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        salarytb = new javax.swing.JTextField();
        deletetabtn = new javax.swing.JButton();
        updatetabtn = new javax.swing.JButton();
        addtabtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        testlbl.setForeground(new java.awt.Color(255, 255, 255));
        testlbl.setText("jLabel13");
        jPanel1.add(testlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 90, 30));

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Teacher Assistants");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 800, 61));

        TAsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TAsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 88, 876, 155));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 30));

        idtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(idtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 130, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-mail");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 30));

        emailtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(emailtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 130, 30));

        fnametb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(fnametb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 130, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 90, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 90, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bank");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 90, 30));

        banktb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(banktb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 130, 30));

        passwordtb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(passwordtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 130, 30));

        lnametb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(lnametb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 130, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Last Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 100, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Salary");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 100, 30));

        salarytb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(salarytb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 130, 30));

        deletetabtn.setBackground(new java.awt.Color(0, 0, 0));
        deletetabtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deletetabtn.setForeground(new java.awt.Color(255, 255, 255));
        deletetabtn.setText("Delete TA");
        jPanel1.add(deletetabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, -1, -1));

        updatetabtn.setBackground(new java.awt.Color(0, 0, 0));
        updatetabtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        updatetabtn.setForeground(new java.awt.Color(255, 255, 255));
        updatetabtn.setText("Update TA");
        jPanel1.add(updatetabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, -1));

        addtabtn.setBackground(new java.awt.Color(0, 0, 0));
        addtabtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addtabtn.setForeground(new java.awt.Color(255, 255, 255));
        addtabtn.setText("Add TA");
        addtabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtabtnActionPerformed(evt);
            }
        });
        jPanel1.add(addtabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, -1, -1));

        backbtn.setBackground(new java.awt.Color(0, 0, 0));
        backbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back to menu");
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 160, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitymanagementsystemclient/GUIs/Grad4.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addtabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtabtnActionPerformed

    }//GEN-LAST:event_addtabtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTAs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTAs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTAs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTAs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTAs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TAsTable;
    private javax.swing.JButton addtabtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField banktb;
    private javax.swing.JButton deletetabtn;
    private javax.swing.JTextField emailtb;
    private javax.swing.JTextField fnametb;
    private javax.swing.JTextField idtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lnametb;
    private javax.swing.JTextField passwordtb;
    private javax.swing.JTextField salarytb;
    private javax.swing.JLabel testlbl;
    private javax.swing.JButton updatetabtn;
    // End of variables declaration//GEN-END:variables
}
