/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymanagementsystemclient.GUIs;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author ahmedwaleed
 */
public class SuperiorAccountInfo extends javax.swing.JFrame {

    /**
     * Creates new form SuperiorAccountInfo
     */
    public SuperiorAccountInfo() {
        initComponents();
    }

    public JLabel getBanklbl() {
        return banklbl;
    }

    public JLabel getEmaillbl() {
        return emaillbl;
    }

    public JLabel getIdlbl() {
        return idlbl;
    }

    public JLabel getNamelbl() {
        return namelbl;
    }

    public JLabel getPasswordlbl() {
        return passwordlbl;
    }

    public JLabel getSalarylbl() {
        return salarylbl;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        banklbl = new javax.swing.JLabel();
        salarylbl = new javax.swing.JLabel();
        passwordlbl = new javax.swing.JLabel();
        emaillbl = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        idlbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Account Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 19, -1, 65));

        jLabel12.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 102, 140, 30));

        jLabel9.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 142, 140, 30));

        jLabel2.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("E-mail");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 182, 140, 30));

        jLabel6.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 222, 140, 30));

        jLabel10.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Salary");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 262, 140, 30));

        jLabel11.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Bank");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 302, 140, 30));

        jButton1.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Return to menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        banklbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        banklbl.setForeground(new java.awt.Color(0, 0, 0));
        banklbl.setText("Name");
        jPanel1.add(banklbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 298, 360, 30));

        salarylbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        salarylbl.setForeground(new java.awt.Color(0, 0, 0));
        salarylbl.setText("ID");
        jPanel1.add(salarylbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 258, 360, 30));

        passwordlbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        passwordlbl.setForeground(new java.awt.Color(0, 0, 0));
        passwordlbl.setText("Name");
        jPanel1.add(passwordlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 222, 360, 30));

        emaillbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        emaillbl.setForeground(new java.awt.Color(0, 0, 0));
        emaillbl.setText("ID");
        jPanel1.add(emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 182, 360, 30));

        namelbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        namelbl.setForeground(new java.awt.Color(0, 0, 0));
        namelbl.setText("Name");
        jPanel1.add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 142, 360, 30));

        idlbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        idlbl.setForeground(new java.awt.Color(0, 0, 0));
        idlbl.setText("ID");
        jPanel1.add(idlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 102, 360, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitymanagementsystemclient/GUIs/abstract-1780378_960_720.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperiorAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperiorAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperiorAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperiorAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperiorAccountInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banklbl;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JLabel idlbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel namelbl;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JLabel salarylbl;
    // End of variables declaration//GEN-END:variables
}
