/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymanagementsystemclient.GUIs;

import javax.swing.JButton;

/**
 *
 * @author ahmedwaleed
 */
public class SuperiorAdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form SuperiorAdminMenu
     */
    public SuperiorAdminMenu() {
        initComponents();
    }

    public JButton getAccinfobtn() {
        return accinfobtn;
    }

    public void setAccinfobtn(JButton accinfobtn) {
        this.accinfobtn = accinfobtn;
    }

    public JButton getMngTAsbtn() {
        return mngTAsbtn;
    }

    public void setMngTAsbtn(JButton mngTAsbtn) {
        this.mngTAsbtn = mngTAsbtn;
    }

    public JButton getMngadminbtn() {
        return mngadminbtn;
    }

    public void setMngadminbtn(JButton mngadminbtn) {
        this.mngadminbtn = mngadminbtn;
    }

    public JButton getMngcoursebtn() {
        return mngcoursebtn;
    }

    public void setMngcoursebtn(JButton mngcoursebtn) {
        this.mngcoursebtn = mngcoursebtn;
    }

    public JButton getMngdoctorsbtn() {
        return mngdoctorsbtn;
    }

    public void setMngdoctorsbtn(JButton mngdoctorsbtn) {
        this.mngdoctorsbtn = mngdoctorsbtn;
    }

    public JButton getMngfacbtn() {
        return mngfacbtn;
    }

    public void setMngfacbtn(JButton mngfacbtn) {
        this.mngfacbtn = mngfacbtn;
    }

    public JButton getSignoutbtn() {
        return signoutbtn;
    }

    public void setSignoutbtn(JButton signoutbtn) {
        this.signoutbtn = signoutbtn;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mngdoctorsbtn = new javax.swing.JButton();
        mngTAsbtn = new javax.swing.JButton();
        mngfacbtn = new javax.swing.JButton();
        mngcoursebtn = new javax.swing.JButton();
        mngadminbtn = new javax.swing.JButton();
        signoutbtn = new javax.swing.JButton();
        accinfobtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        mngdoctorsbtn.setBackground(new java.awt.Color(0, 0, 0));
        mngdoctorsbtn.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        mngdoctorsbtn.setForeground(new java.awt.Color(255, 255, 255));
        mngdoctorsbtn.setText("Manage Doctors");
        jPanel1.add(mngdoctorsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 60));

        mngTAsbtn.setBackground(new java.awt.Color(0, 0, 0));
        mngTAsbtn.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        mngTAsbtn.setForeground(new java.awt.Color(255, 255, 255));
        mngTAsbtn.setText("Manage TAs");
        jPanel1.add(mngTAsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 220, 60));

        mngfacbtn.setBackground(new java.awt.Color(0, 0, 0));
        mngfacbtn.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        mngfacbtn.setForeground(new java.awt.Color(255, 255, 255));
        mngfacbtn.setText("Manage Faculties");
        jPanel1.add(mngfacbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 230, 60));

        mngcoursebtn.setBackground(new java.awt.Color(0, 0, 0));
        mngcoursebtn.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        mngcoursebtn.setForeground(new java.awt.Color(255, 255, 255));
        mngcoursebtn.setText("Manage Courses");
        jPanel1.add(mngcoursebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 220, 60));

        mngadminbtn.setBackground(new java.awt.Color(0, 0, 0));
        mngadminbtn.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        mngadminbtn.setForeground(new java.awt.Color(255, 255, 255));
        mngadminbtn.setText("Maanage Admins");
        jPanel1.add(mngadminbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 220, 60));

        signoutbtn.setBackground(new java.awt.Color(0, 0, 0));
        signoutbtn.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        signoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        signoutbtn.setText("Sign Out");
        jPanel1.add(signoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 160, 40));

        accinfobtn.setBackground(new java.awt.Color(0, 0, 0));
        accinfobtn.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        accinfobtn.setForeground(new java.awt.Color(255, 255, 255));
        accinfobtn.setText("Account Info");
        jPanel1.add(accinfobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 220, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universitymanagementsystemclient/GUIs/Grad2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accinfobtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mngTAsbtn;
    private javax.swing.JButton mngadminbtn;
    private javax.swing.JButton mngcoursebtn;
    private javax.swing.JButton mngdoctorsbtn;
    private javax.swing.JButton mngfacbtn;
    private javax.swing.JButton signoutbtn;
    // End of variables declaration//GEN-END:variables
}
